defaults:
  - model: bc_lm
  - dataset: list_val
  - evaluator: bc_evaluator
  - _self_

dataset:
  cache_id: d
  agent_role: seller

model:
  transition_weight: 0.0
  dataset:
    name: craigslist_list_dataset
    cache_id: d
  load:
    checkpoint_path: outputs/craigslist/craigslist_seller_bc_test1/model.pkl
    strict_load: true

evaluator:
  env:
    dataset:
      name: craigslist_list_dataset
      cache_id: d
    policy:
      name: bc_policy
      bc_lm:
        name: bc_lm
        dataset:
          name: craigslist_list_dataset
          cache_id: d
        transition_weight: 0.0
        load:
          name: bc_lm
          checkpoint_path: outputs/craigslist/craigslist_buyer_bc_test1/model.pkl
          strict_load: true
      kind: sample
      generation_kwargs: {}
    agent_role: seller

eval:
  dataloader_workers: 1
  bsize: 1
  batches: 1024
  print_every: 8
  seed: 0
  log_save_path: null
  loss: {}

