defaults:
  - model: bc_lm
  - dataset@train_dataset: list_train
  - dataset@eval_dataset: list_val
  - evaluator: bc_generation_evaluator
  - _self_

train_dataset:
  cache_id: d_train
  agent_role: seller

eval_dataset:
  cache_id: d_eval
  agent_role: seller

model:
  transition_weight: 0.0
  dataset:
    name: craigslist_list_dataset
    cache_id: d_train
  load:
    checkpoint_path: null
    strict_load: true

evaluator:
  data:
    name: craigslist_list_dataset
    cache_id: d_eval
  agent_role: seller
  kind: sample
  generation_kwargs: {}

train:
  save_checkpoint_dir: outputs/craigslist/craigslist_seller_bc_test1/
  optim_state_path: null
  epochs: 10000000
  dataloader_workers: 1
  bsize: 2
  grad_accum_steps: 8
  log_every: 256
  eval_every: 1024
  save_every: 16384
  max_checkpoints: 1
  eval_bsize: 2
  eval_batches: 1
  lr: 1e-4
  weight_decay: 0.00
  max_steps: null
  loss: {}

wandb:
  use_wandb: false
  wandb_project: craigslist_bc
