defaults:
  - model: per_token_iql
  - dataset@train_dataset: list_train
  - dataset@eval_dataset: list_val
  - evaluator: iql_evaluator
  - _self_

train_dataset:
  cache_id: d_train
  agent_role: seller
  max_len: 983

eval_dataset:
  cache_id: d_eval
  agent_role: seller
  max_len: 983

model:
  alpha: 0.005
  gamma: 0.99
  beta: 0.0
  transition_weight: 0.0
  clip_weight: null
  value_max: null
  value_min: null
  detach_v: false
  detach_q: false
  detach_pi: false
  double_q: true
  seperate_policy: true
  seperate_target: true
  tau: 0.8
  exp_weights: true
  dm_margin: 0.0
  advanced_mlp: false
  cql_temp: 1.0
  gpt2:
    lm_head: true
    from_pretrained: true
  dataset:
    name: craigslist_list_dataset
    cache_id: d_train
  load:
    checkpoint_path: outputs/craigslist/craigslist_seller_bc_test1/model_converted.pkl
    strict_load: false

evaluator:
  env:
    dataset:
      name: craigslist_list_dataset
      cache_id: d_eval
    policy:
      name: bc_policy
      bc_lm:
        name: bc_lm
        gpt2:
          name: gpt2
          gpt2_type: gpt2
          from_pretrained: true
          lm_head: true
        dataset:
          name: craigslist_list_dataset
          cache_id: d_train
        transition_weight: 0.0
        load:
          name: bc_lm
          checkpoint_path: outputs/craigslist/craigslist_buyer_bc_test1/model.pkl
          strict_load: true
      kind: sample
      generation_kwargs:
        max_generation_len: 40
    agent_role: seller
    max_turns: 10
  kind: sample
  generation_kwargs:
    max_generation_len: 40
    # beam_width: 1
    temp: 1.0
    top_k: null
    top_p: null
    exp_adv: true
    adv_weight: 16.0
    adv_clip: null
    include_logits: true
    include_adv: true
    num_generations: 1
    rerank_log_prob_weight: 0.0
    rerank_advantage_weight: 1.0

train:
  save_checkpoint_dir: outputs/craigslist/craigslist_iql_test1/
  optim_state_path: null
  epochs: 10000000
  dataloader_workers: 1
  bsize: 1
  grad_accum_steps: 64
  log_every: 256
  eval_every: 8192
  save_every: 16384
  max_checkpoints: 1
  eval_bsize: 1
  eval_batches: 32
  lr: 1e-5
  weight_decay: 0.00
  hard_update_every: null
  max_steps: null
  loss:
    v_loss_weight: 1.0
    q_loss_weight: 1.0
    awac_weight: 0.0
    cql_loss_weight: 1.0
    dm_loss_weight: 0.0
    mc_returns: false

wandb:
  use_wandb: true
  wandb_project: craigslist_iql
